require: rubocop-rspec
require: rubocop-performance

AllCops:
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'db/**'

Layout/LineLength:
  Max: 130

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/CaseEquality:
  Enabled: false

Naming/PredicateName:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb

Style/ModuleFunction:
  Enabled: false
